### ISSUE TITLE
faraday gem not found

### ISSUE THREAD

**Issue by Conzar** [fsalum/puppet-slack#3]
Running the module on Ubuntu 14.04 LTS.  

When I execute a puppet agent -t, the following error is reported

```
Error: Could not send report: Error 400 on SERVER: Could not autoload puppet/reports/slack: cannot load such file -- faraday
```

I can manually install faraday via

```
sudo gem install faraday
```

Which removes this problem but isn't very puppet like.

**Comment by fsalum** [comment]
@Conzar faraday gem should be installed by this module, see https://github.com/fsalum/puppet-slack/blob/master/manifests/init.pp#L12

Do you know if puppet failed to install the gem on the first run for some reason ?

**Comment by Conzar** [comment]
I ran puppet agent -t multiple times, but it didn't seem to have any effect on the gem install.

**Comment by fsalum** [comment]
I'd recommend you to run some tests to find out why the puppet gem provider is not working in your server.
