### ISSUE TITLE
Class Slack already defined

### ISSUE THREAD

**Issue by Conzar** [fsalum/puppet-slack#4]
After installing farady manually, running puppet agent -t gives the following error:

```
Error: Could not send report: Error 400 on SERVER: Could not autoload puppet/reports/slack: Class Slack is already defined in Puppet::Reports
```

Any where besides slack.rb has this bit:

```
Puppet::Reports.register_report(:slack) 
```

Could slack.rb be installed in multiple places some how? ... hummm.
I have multiple environments with this class in each environment.  The puppet master is running the production environment though.

**Comment by fsalum** [comment]
I see this kind of issue mentioned on http://projects.puppetlabs.com/issues/17883 but I'm not getting the error you have on my environment. 

Are you using my latest version of the module ? And puppet version ?

**Comment by Conzar** [comment]
I am using the version from puppet forge 0.0.1.
Puppet version: 3.6.2

**Comment by fsalum** [comment]
Can you keep the class only in your prod environment and test?

**Comment by Conzar** [comment]
Actually, I have only installed it on the production environment.  So that doesn't seem to be the issue.

**Comment by alexm** [comment]
FWIW, this issue is currently tracked by Puppetlabs in https://tickets.puppetlabs.com/browse/PUP-1189 and it happens when the report processor has some error.

The quick workaround is to restart the puppetmaster after fixing the report processor error.
