### ISSUE TITLE
Puppetserver requires gems to be installed through puppetserver command

### ISSUE THREAD

**Issue by Conzar** [fsalum/puppet-slack#5]
The following command is required if using the new puppetserver to work with the slack module.

```
puppetserver gem install faraday
```

**Comment by fsalum** [comment]
I need to install the new puppet server to look at it. Can you submit a pull request? It need to be able to find out if it is the new puppet server or puppet master to install the gem correctly.

**Comment by Conzar** [comment]
Ok, I have added a pull request which handles the new puppetserver.
